version: "3"
services:
  app:
    image: ilyakarachun/hospital
    container_name: container-hospital
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
